spring:
  profiles:
    active: test
---
spring:
  application:
    name: account_service
  profiles: [test, default]
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false

rememberit:
    oauth_uri: http://localhost:9998/oauth/check_token
    client_id: fooClientIdSecret
    client_secret: secret
