spring:
  profiles:
    active: test
---
spring:
  application:
    name: oauth2_service
  profiles: [test, default]
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false

spring.h2.console:
  enabled: true
  path: /h2-console
